### PR TITLE
NOJIRA: chore: Update to dotnet 8 + ef core 8

### PR DESCRIPTION
**Pull request by DylanSnel**
No Jira ticket available. 

I made sure the provider runs with dotnet 8 using the latest packages. For some reason Assert.Equivalent wouldnt work anymore. I ran tests to see if my change has the correct result and it did. This felt like something out of my control, so i decided not to change that.

This is my first PR on GitHub, so if i did something wrong with this please let me know so i can learn.
I also didn't know how to update the version number of the package.

### CODE REVIEW

**Comment by damieng** [comment]
Hi Dylan.

Thanks for your contribution. I'm trying to merge this in but there are a few issues.

We typically do these things in steps - e.g. upgrade deps, switch to .NET 8, then migrate to EF etc. otherwise we can't tell what caused what.

I've gone ahead and done the required deps and .NET 8 switch and merged that into main. I'm looking at bringing your EF 8 work in on top of this but am running into issues specifically that you haven't allowed maintainers modify access to your fork so I can't resolve the conflicts and test them on our CI before merging. (Ditto the GitHub web ui).

Can you allow maintainer access to modify your fork?

**Comment by DylanSnel** [comment]
Hey @damieng 

image

This setting is checked, is there anything else i should check?

**Comment by damieng** [comment]
I think it's a permission on the fork itself? 
image

**Comment by damieng** [comment]
Hmm, from GitHub's docs the checkbox you ticked should be enough.

**Comment by damieng** [comment]
I have no idea now why this closed just by me updating your branch. Sorry. Forks and needing to tweak them are infrequent and fiddly enough that they never seem to go right.

**Comment by DylanSnel** [comment]
How can we fix this?

**Comment by DylanSnel** [comment]
Maybe its cause its a main branch for my repo.. im kinda new to forks

**Comment by damieng** [comment]
There are a few scenarios, specifically:

1. Working on my own forks/branches
2. Accepting PR's as-is from others
3. Needing to adjust other people's PRs/forks before proceeding

Scenario 3 happens infrequently enough and is non-obvious that it's always a pain. I'll keep trying to figure this out and let you know.

**Comment by damieng** [comment]
Okay, stuck in a scenario now where I can't re-open the PR and because there's nothing on main after I force pushed I also can't push to your repo to correct that because the PR is closed.

**Comment by damieng** [comment]
Hi.

I've managed to rebase and cherry-pick to a new branch here, hope that's okay. https://github.com/mongodb/mongo-efcore-provider/pull/55 still has your name on the commit.

**Comment by DylanSnel** [comment]
Yeah of course no problem. I was just happy to help. I really hope you guys get ValueConverters working. That would make it so awesome. Since i ran into a problem with Domain Driven Design using an interceptor. 

Anyways Good luck!

**Comment by damieng** [comment]
Value Converters are on the backlog - just a lot of stuff to get through!

**Comment by DylanSnel** [comment]
Oh yeah it looked very complex

**Pull request closed without merging**
